# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: replace with version
  displayName: 'Run a one-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x.x'  # Replace with the version of .NET you're using
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: restore nuget packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  # This will restore NuGet packages

- script: build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'  # Build the solution

- script: publish project 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'  # Publish the project