# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: "Default"   
 

steps:
# Checkout the code
- task: Checkout@1

# Build the ASP.NET Core project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

# Deploy the build to IIS using PowerShell or direct file copy since the agent is in the local network
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path "$(Build.ArtifactStagingDirectory)\*" -Destination "C:\inetpub\wwwroot\PipeLineAgent" -Recurse
      iisreset  # Restart IIS (optional)